steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--push', '-t', 'gcr.io/adarsh-web-1111/testing', '.' ]

serviceAccount: 'projects/adarsh-web-1111/serviceAccounts/adarsh-web-1111@appspot.gserviceaccount.com'
timeout: '10800s'
options:
  logging: CLOUD_LOGGING_ONLY