steps:
  - name: ubuntu
    args:
      - /bin/bash
      - '-c'
      - |
        echo "Hello, world!"
        sleep 30  # Sleep for 5 minutes (30 seconds)
options:
  pool:
    name: projects/adarsh-web-1111/locations/asia-south1/workerPools/cloud-build-private