steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/adarsh-web-1111/test/ubuntu:v1', '.' ]

serviceAccount: 'projects/adarsh-web-1111/serviceAccounts/adarsh-web-1111@appspot.gserviceaccount.com'
timeout: '10800s'
options:
  logging: CLOUD_LOGGING_ONLY